specVersion: 0.2.0
name: 'historical-balance'
version: "0.0.0"
description: ''
repository: ''
schema:
  file: "./schema.graphql"
network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  genesisHash: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
dataSources:
  - kind: substrate/Runtime
    startBlock: 7560558
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
